apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      containers:
      - name: pushgateway
        image: prom/pushgateway:latest
        ports:
        - containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: pushgateway-service
spec:
  selector:
    app: pushgateway
  ports:
  - port: 9091
    targetPort: 9091
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: robot-metrics-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: robot-metrics-generator
  template:
    metadata:
      labels:
        app: robot-metrics-generator
    spec:
      containers:
      - name: generator
        image: alpine/curl:latest
        command: ["/bin/sh"]
        args: ["/scripts/healthy-datacenter-metrics.sh"]
        volumeMounts:
        - name: metrics-script
          mountPath: /scripts
        env:
        - name: PUSHGATEWAY_URL
          value: "http://pushgateway-service:9091"
      volumes:
      - name: metrics-script
        configMap:
          name: robot-metrics-server
          defaultMode: 0755
