apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      containers:
      - name: pushgateway
        image: prom/pushgateway:latest
        ports:
        - containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: pushgateway-service
spec:
  selector:
    app: pushgateway
  ports:
  - port: 9091
    targetPort: 9091
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dual-region-metrics-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dual-region-metrics-generator
  template:
    metadata:
      labels:
        app: dual-region-metrics-generator
    spec:
      initContainers:
      - name: install-deps
        image: python:3.9-slim
        command: ["sh", "-c"]
        args:
        - |
          pip install requests
          touch /deps/ready
        volumeMounts:
        - name: deps
          mountPath: /deps
      containers:
      - name: generator
        image: python:3.9-slim
        command: ["sh", "-c"]
        args:
        - |
          pip install requests
          python /app/dual_region_metrics_server.py
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: metrics-script
          mountPath: /app
        - name: deps
          mountPath: /deps
        env:
        - name: PUSHGATEWAY_URL
          value: "http://pushgateway-service:9091"
      volumes:
      - name: metrics-script
        configMap:
          name: robot-metrics-server
          defaultMode: 0755
      - name: deps
        emptyDir: {}
